# Generated by Django 5.0.4 on 2024-04-22 19:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="watcher_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fid", models.FloatField()),
                ("name", models.CharField(max_length=50)),
                ("size", models.FloatField()),
                ("crop", models.CharField(max_length=10)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name="watcher_mod",
        ),
    ]
