# Generated by Django 5.0.4 on 2024-05-14 14:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0003_alter_watcher_model_geom"),
    ]

    operations = [
        migrations.CreateModel(
            name="farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fid", models.FloatField()),
                ("name", models.CharField(max_length=50)),
                ("size", models.FloatField()),
                ("crop", models.CharField(max_length=10)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="watcher_model",
        ),
    ]
