# Generated by Django 5.0.6 on 2024-05-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watcher", "0004_farm_delete_watcher_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="ndmi_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="ndvi_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="ndwi_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
